baseURL: https://blog.xuhui.dev/
title: xuhui
theme: PaperMod
defaultContentLanguage: zh

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

languages:
  zh:
    languageName: "简体中文"
    weight: 1
    menu:
      main:
        - name: 分类
          url: categories
          weight: 5
        - name: 专栏
          url: series/
          weight: 10
        - name: 标签
          url: tags/
          weight: 10
        - name: 搜索
          url: search
        - name: Rss
          url: index.xml
    homeInfoParams:
      Title: "生存, 活着 != 生活"
      Content: >
        "不自由，毋宁死"


        生活其实没有什么不易, 没人能强迫你.

  en:
    languageName: "English"
    weight: 2
    menu:
      main:
        - name: Categories
          url: categories
          weight: 5
        - name: Tags
          url: tags/
          weight: 10
        - name: Series
          url: series/
          weight: 10
        - name: Search
          url: search
        - name: Rss
          url: index.xml
    homeInfoParams:
      Title: "Ok."
      Content: >
        Give me liberty or give me death.

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "xuhui's pages: a web developer."
  author: xuhui

  defaultTheme: auto
  # ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # images: ["papermod-cover.png"]

  # socialIcons:
  #   - name: github
  #     url: "https://github.com/adityatelange/hugo-PaperMod"
  #   - name: KoFi
  #     url: "https://ko-fi.com/adityatelange"
  #   - name: Rss
  #     url: "index.xml"
